function test_eliminatesimilarseqs
% TEST_ELIMINATESIMILARSEQS Test eliminatesimilarseqs.m.

mockalign = alnmake([...
    'AAAAAAAAAA' ; ...
    'AACDAAAAAA' ; ...
    'A-FGAAAAAA' ; ...
    'CCCCCCCCCC' ; ...
    'CC-CCCCCCC' ; ...
    'CCC-CCCCCC' ; ...
    'CC--CCCCCC'], 'protein');
mockalign_f1 = eliminatesimilarseqs(mockalign, 0.75);
mockalign_f1_exp = alnmake([...
    'AAAAAAAAAA' ; ...
    'A-FGAAAAAA' ; ...
    'CCCCCCCCCC'], 'protein');
utexpect(alncompare(mockalign_f1, mockalign_f1_exp), 'eliminatesimilar threshold 0.75');

mockalign_f2 = eliminatesimilarseqs(mockalign, 0.85);
mockalign_f2_exp = alnmake([...
    'AAAAAAAAAA' ; ...
    'AACDAAAAAA' ; ...
    'A-FGAAAAAA' ; ...
    'CCCCCCCCCC'], 'protein');
utexpect(alncompare(mockalign_f2, mockalign_f2_exp), 'eliminatesimilar threshold 0.85');

global multicov_ut_cpppolicy;

if eliminatesimilarseqs('hascpp')
    mockalign_f2_ml = eliminatesimilarseqs(mockalign, 0.85, 'nocpp', true);
    utexpect(alncompare(mockalign_f2, mockalign_f2_ml), 'eliminiatesimilar Matlab version (no C++)');
else
    if strcmp(multicov_ut_cpppolicy, 'warn')
        warning([mfilename ':nocpp'], 'Cannot find C++ extension for eliminatesimilarseqs. Please compile the extension for optimal performance.');
    elseif strcmp(multicov_ut_cpppolicy, 'fail')
        utexpect(false, 'eliminatesimilarseqs C++ extension missing');
    end
end

end