function res = genalncheck(alignment)
% GENALNCHECK Internal function.
%
% Check that the structure has the common fields for an alignment, whether
% character or binary.
%   res = GENALNCHECK(alignment) returns true if the argument has the
%   appropriate fields that are common for alignments (whether character or
%   binary).

% Tiberiu Tesileanu (2014)

res = (...
    all(isfield(alignment, {'alphabets', 'alphawidths', 'data', 'seqw', 'type', 'refseq', 'annotations'})) && ...
    ischar(alignment.type) && isvector(alignment.type) && ...
    iscell(alignment.alphabets) && ...
    (isvector(alignment.alphawidths) || isempty(alignment.alphawidths)) && ...
    isnumeric(alignment.alphawidths) && ...
    (isvector(alignment.seqw) || isempty(alignment.seqw)) && ...
    isnumeric(alignment.seqw) && ...
    iscell(alignment.annotations) && ...
    isstruct(alignment.refseq));

end