function test_getdbseq
% TEST_GETDBSEQ Test getdbseq.m

dlg4id = 'DLG4_RAT';
dlg4acc = 'P31016';

dlg4rat_seq_exp = [...
    'MDCLCIVTTKKYRYQDEDTPPLEHSPAHLPNQANSPPVIVNTDTLEAPGYELQVNGTEGE' ...
    'MEYEEITLERGNSGLGFSIAGGTDNPHIGDDPSIFITKIIPGGAAAQDGRLRVNDSILFV' ...
    'NEVDVREVTHSAAVEALKEAGSIVRLYVMRRKPPAEKVMEIKLIKGPKGLGFSIAGGVGN' ...
    'QHIPGDNSIYVTKIIEGGAAHKDGRLQIGDKILAVNSVGLEDVMHEDAVAALKNTYDVVY' ...
    'LKVAKPSNAYLSDSYAPPDITTSYSQHLDNEISHSSYLGTDYPTAMTPTSPRRYSPVAKD' ...
    'LLGEEDIPREPRRIVIHRGSTGLGFNIVGGEDGEGIFISFILAGGPADLSGELRKGDQIL' ...
    'SVNGVDLRNASHEQAAIALKNAGQTVTIIAQYKPEEYSRFEAKIHDLREQLMNSSLGSGT' ...
    'ASLRSNPKRGFYIRALFDYDKTKDCGFLSQALSFRFGDVLHVIDAGDEEWWQARRVHSDS' ...
    'ETDDIGFIPSKRRVERREWSRLKAKDWGSSSGSQGREDSVLSYETVTQMEVHYARPIIIL' ...
    'GPTKDRANDDLLSEFPDKFGSCVPHTTRPKREYEIDGRDYHFVSSREKMEKDIQAHKFIE' ...
    'AGQYNSHLYGTSVQSVREVAEQGKHCILDVSANAVRRLQAAHLHPIAIFIRPRSLENVLE' ...
    'INKRITEEQARKAFDRATKLEQEFTECFSAIVEGDSFEEIYHKVKRVIEDLSGPYIWVPA' ...
    'RERL'];
timer = tic;
[dlg4rat_seq, dlg4rat_info] = getdbseq('uniprot', dlg4id);

utexpect(strcmp(dlg4rat_info.db, 'uniprot') && ...
    strcmp(dlg4rat_seq, dlg4rat_seq_exp) && ...
    strcmp(dlg4rat_info.id, dlg4id) && ...
    strcmp(dlg4rat_info.accession, dlg4acc), ...
    'getdbseq uniprot search auto (by id)', timer);

timer = tic;
[dlg4rat_seq2, dlg4rat_info2] = getdbseq('uniprot', dlg4acc);

utexpect(strcmp(dlg4rat_seq2, dlg4rat_seq) && ...
    strcmp(dlg4rat_info2.id, dlg4id) && ...
    strcmp(dlg4rat_info2.accession, dlg4acc), ...
    'getdbseq uniprot search auto (by accession number)', timer);

timer = tic;
[dlg4rat_seq2, dlg4rat_info2] = getdbseq('uniprot', dlg4id, 'idtype', 'id');

utexpect(strcmp(dlg4rat_seq2, dlg4rat_seq_exp) && ...
    strcmp(dlg4rat_info2.id, dlg4id) && ...
    strcmp(dlg4rat_info2.accession, dlg4acc), ...
    'getdbseq uniprot search by id', timer);

global multicov_ut_dir;

timer = tic;
pdb = pdbread(fullfile(multicov_ut_dir, 'data', '3TGI.pdb'));
pdb_chain = 'E';

[seq_3tgi, info_3tgi] = getdbseq({pdb, pdb_chain});

id_3tgi = 'TRY2_RAT';
acc_3tgi = 'P00763';
seq_3tgi_exp = [...
    'MRALLFLALVGAAVAFPVDDDDKIVGGYTCQENSVPYQVSLNSGYHFCGGSLINDQWVVS' ...
    'AAHCYKSRIQVRLGEHNINVLEGNEQFVNAAKIIKHPNFDRKTLNNDIMLIKLSSPVKLN' ...
    'ARVATVALPSSCAPAGTQCLISGWGNTLSSGVNEPDLLQCLDAPLLPQADCEASYPGKIT' ...
    'DNMVCVGFLEGGKDSCQGDSGGPVVCNGELQGIVSWGYGCALPDNPGVYTKVCNYVDWIQ' ...
    'DTIAAN'];

utexpect(strcmp(info_3tgi.db, 'uniprot') && ...
    strcmp(seq_3tgi, seq_3tgi_exp) && ...
    strcmp(id_3tgi, info_3tgi.id) && ...
    strcmp(acc_3tgi, info_3tgi.accession) && ...
    length(pdb.Sequence(1).Sequence) == length(info_3tgi.range), ...
    'getdbseq uniprot search from pdbs', timer);

% now for some tRNA
timer = tic;
pdb = pdbread(fullfile(multicov_ut_dir, 'data', '4TNA.pdb'));
pdb_chain = 'A';

[~, info_4tna] = getdbseq({pdb, pdb_chain});
utexpect(strcmp(info_4tna.db, 'pdb') && ...
    strcmp(info_4tna.id, '4TNA'), ...
    'getdbseq with tRNA sequence, basic test', timer);

end