function test_alphagetletters
% TEST_ALPHAGETLETTERS Test alphagetletters.m.

% test that all the alphabets in the list are indeed supported
alphas = alphagetletters('list');
utexpect(all(ismember({'protein', 'dna', 'rna', 'binary'}, alphas)), ...
    'alphagetletters basic alphabets exist');

for i = 1:length(alphas)
    alphabet = alphas{i};
    gapalphabet = ['gap' alphabet];
    letters = alphagetletters(alphabet);
    gapletters = alphagetletters(gapalphabet);
    
    letters_ng = alphagetletters(alphabet, 'nogap');
    gapletters_ng = alphagetletters(gapalphabet, 'nogap');
    
    utexpect(length(gapletters) == length(letters) + 1 && ...
        length(setdiff(gapletters, letters)) == 1 && ...
        length(letters) == length(letters_ng) + 1 && ...
        length(setdiff(letters, letters_ng)) == 1 && ...
        strcmp(gapletters_ng, letters) && ...
        strcmp(letters_ng, letters(2:end)), ...
        ['alphagetletters ' alphabet ' with and without gaps']);
end

utexpect(strcmp(alphagetletters('dna', 'nogap'), 'ACGT') && ...
    strcmp(alphagetletters('rna', 'nogap'), 'ACGU') && ...
    strcmp(alphagetletters('protein' ,'nogap'), 'ACDEFGHIKLMNPQRSTVWY'), ...
    'alphagetletters correct results for dna, rna, protein');

end