function istats = statscheck(stats)
% STATSCHECK Check that the argument is a statistics structure.
%   isstats = STATSCHECK(stats) checks that the argument is a valid statistics
%   structure. This should contain fields 'type', 'alphabets', 'alphawidths',
%   'refseq', 'freq1', 'cmat', and optionally 'freq2'. 'Type' should be equal
%   to 'stats'.
%
% See also: ALNMAKE, ALNCHECK, BINCHECK, PARAMSCHECK.

% Tiberiu Tesileanu (2013-2014)

istats = (...
    all(isfield(stats, {'type', 'freq1', 'cmat', 'alphabets', 'alphawidths', 'refseq'})) && ...
    strcmp(stats.type, 'stats') && ...
    iscell(stats.alphabets) && ...
    (isvector(stats.alphawidths) || isempty(stats.alphawidths)) && ...
    isnumeric(stats.alphawidths) && ...
    isstruct(stats.refseq) && ...
    isvector(stats.freq1) && isnumeric(stats.freq1) && ...
    ismatrix(stats.cmat) && isnumeric(stats.cmat) && ...
    (~isfield(stats, 'freq2') || (ismatrix(stats.freq2) && isnumeric(stats.freq2))) ...
);

end