function isparams = paramscheck(params)
% PARAMSCHECK Check that the argument is a maximum entropy model parameters
% structure.
%   isparams = PARAMSCHECK(params) checks that the argument is a valid
%   structure containing maximum entropy model parameters. This should
%   contain fields 'type', 'alphabets', 'alphawidths', 'couplings', and
%   'refseq'. 'Type' should be equal to 'maxent'.
%
% See also: ALNMAKE, ALNCHECK, BINCHECK, STATSCHECK.

% Tiberiu Tesileanu (2014)

isparams = (...
    all(isfield(params, {'type', 'alphabets', 'alphawidths', 'refseq', 'couplings'})) && ...
    strcmp(params.type, 'maxent') && ...
    iscell(params.alphabets) && ...
    (isvector(params.alphawidths) || isempty(params.alphawidths)) && ...
    isnumeric(params.alphawidths) && ...
    isstruct(params.refseq) && ...
    ismatrix(params.couplings) && isnumeric(params.couplings) ...
);

end